### ISSUE TITLE
[Ask a question]ping

### ISSUE THREAD

**Issue by Sanj1Ng** [dysphie/nmrih-ping-system#2]
How do I set up to use ping every 10 seconds?
I modified it：
sm_ping_cooldown_bucket_size "1"
sm_ping_cooldown_tokens_per_second "10"

But it doesn't seem to work，Players can still use it 3 times。
Please help me

**Comment by dysphie** [comment]
You can think of the cooldown system like stamina

`sm_ping_cooldown_bucket_size` is how many ping tokens you start with, sending a ping takes one token
`sm_ping_cooldown_tokens_per_second` is how many new tokens you regain per second

If you want to limit the use of pings to one ping every 10 seconds, you can use the following values:
```
sm_ping_cooldown_bucket_size 1
sm_ping_cooldown_tokens_per_second 0.1
```

I hope this helps

**Comment by Sanj1Ng** [comment]
> 你能想到的冷却系统，如耐力
> 
> `sm_ping_cooldown_bucket_size` 是多少平币开始，发送平需要一个令牌 `sm_ping_cooldown_tokens_per_second` 是的如何许多新的令牌你重新获得每秒
> 
> 如果你想要限制使用坪的一个平，每10秒钟，就可以使用以下价值观：
> 
> ```
> sm_ping_cooldown_bucket_size 1
> sm_ping_cooldown_tokens_per_second 0.1
> ```
> 
> 我希望这可以帮助

非常感谢

**Comment by Sanj1Ng** [comment]
> You can think of the cooldown system like stamina
> 
> `sm_ping_cooldown_bucket_size` is how many ping tokens you start with, sending a ping takes one token `sm_ping_cooldown_tokens_per_second` is how many new tokens you regain per second
> 
> If you want to limit the use of pings to one ping every 10 seconds, you can use the following values:
> 
> ```
> sm_ping_cooldown_bucket_size 1
> sm_ping_cooldown_tokens_per_second 0.1
> ```
> 
> I hope this helps

Thank you very much
