### ISSUE TITLE
Windows environment compilation failed

### ISSUE THREAD

**Issue by F1F88** [dysphie/nmrih-ping-system#3]
Is it my fault that the Windows environment compilation failed?
Perhaps there is also a lack of morecolors.inc

Version:
Mmsource-1.11.0-git1148-windows
Sourcemod-1.11.0-git6934-windows

![image](https://github.com/dysphie/nmrih-ping-system/assets/66011476/f9e5f651-e4e4-4f40-92c0-81951b325c75)

**Comment by dysphie** [comment]
You need Sourcemod 1.12 to compile, morecolors.inc can be found [here](https://forums.alliedmods.net/showthread.php?t=185016)

**Comment by F1F88** [comment]
Thank you. After upgrading to Sourcemod 1.12, the compilation was successful. 
So does the SourceMod 1.11 or higher mentioned in Requirements in readme refer to the runtime environment?

**Comment by dysphie** [comment]
yes, the requirements in the readme are for running the plugin in a server, not compiling it
